spring.application.name=point_of_Sale
server.port = 5000
spring.datasource.url=jdbc:mysql://localhost:3306/pos_2569_term1
spring.datasource.username = root
spring.datasource.password =1234
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql =true